
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('planitems').del()
    .then(function () {
      // Inserts seed entries
      return knex('planitems').insert([
        //***************************** PLAN DE PASSATION DES MARCHES DU SIEGE**********/
        {id: 1, 
         plan_id: 1, 
         budget_id: 1, 
         imputation: '220', 
         montant_estime: 770200000, 
         montant_depense: 0, 
         credit: 770200000, 
         designation: 'Travaux de construction des infrastructures du 11 décembre 2021 dans la région du plateau central ZINIARE', 
         nbr_lot: 5, 
         mode_id: 1,
         periode_lanc: '22-02-2021',
         periode_remise: '24-03-2021',
         temp: 3,
         date_prob_demarrage: '23-04-2021',
         delai_exe: 120, 
         date_prob_fin: '21-08-2021',
         gestionnaire: 'DESG',
         type_id: 1,
         localisation_id: 1
        },
        {id: 2, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '220',
          montant_estime: 68100000, 
          montant_depense: 0, 
          credit: 68100000, 
          designation: 'Travaux de construction de deux villas F4  avec annexes sur les deux parcelles abritant la SMI mobile de Tampaouy à Ouagadougou', 
          nbr_lot: 1, 
          mode_id: 3,
          periode_lanc: '23-02-2021',
          periode_remise: '05-03-2021',
          temp: 1,
          date_prob_demarrage: '04-04-2021',
          delai_exe: 120, 
          date_prob_fin: '02-08-2021',
          gestionnaire: 'DESG',
          type_id: 1,
          localisation_id: 1
         },
         {id: 3, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '222', 
          montant_estime: 278175000, 
          montant_depense: 0, 
          credit: 278175000, 
          designation: 'Acquisition de matériels informatiques & autres matériels informatiques', 
          nbr_lot: 4, 
          mode_id: 1,
          periode_lanc: '23-02-2021',
          periode_remise: '25-03-2021',
          temp: 3,
          date_prob_demarrage: '24-04-2021',
          delai_exe: 90, 
          date_prob_fin: '23-07-2021',
          gestionnaire: 'DSI',
          type_id: 2,
          localisation_id: 1 
         },
         {id: 4, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '223', 
          montant_estime: 27000000, 
          montant_depense: 0, 
          credit: 27000000, 
          designation: 'Entretien annuel du parc climatique du bâtiment A et B, du CFP, de la DPASS et du SPAS', 
          nbr_lot: 1, 
          mode_id: 4,
          periode_lanc: '23-02-2021',
          periode_remise: '05-03-2021',
          temp: 1,
          date_prob_demarrage: '04-04-2021',
          delai_exe: 360, 
          date_prob_fin: '30-03-2023',
          gestionnaire: 'DESG',
          type_id: 2,
          localisation_id: 1
         },
         {id: 5, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '634', 
          montant_estime: 12000000, 
          montant_depense: 0, 
          credit: 12000000, 
          designation: 'Sélection de deux cabinets d\'expertise comptable pour les prestation de commissariat aux comptes', 
          nbr_lot: 1, 
          mode_id: 10,
          periode_lanc: '05-01-2020',
          periode_remise: '15-01-2020',
          temp: 1,
          date_prob_demarrage: '30-01-2020',
          delai_exe: 360, 
          date_prob_fin: '24-01-2021',
          gestionnaire: 'DFC',
          type_id: 3,
          localisation_id: 1
         },
         {id: 6, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '203', 
          montant_estime: 29800000, 
          montant_depense: 0, 
          credit: 29800000, 
          designation: 'Suivi-contrôle des travaux de Construction des infrastructures du 11 décembre 2021 dans la région de plateau central à ZINIARE', 
          nbr_lot: 1, 
          mode_id: 4,
          periode_lanc: '22-02-2021',
          periode_remise: '04-03-2021',
          temp: 1,
          date_prob_demarrage: '03-04-2021',
          delai_exe: 180, 
          date_prob_fin: '30-09-2021',
          gestionnaire: 'DESG',
          type_id: 3,
          localisation_id: 1
         },
         //***************************** PLAN DE PASSATION DES MARCHES DE LA DIRECTION REGIONALE DE OUAGADOUGOU**********/
        {id: 7, 
         plan_id: 1, 
         budget_id: 1, 
         imputation: '220', 
         montant_estime: 1500000, 
         montant_depense: 0, 
         credit: 1500000, 
         designation: 'Travaux de construction de toilettes externes au domicile du responsable de bureau de Poura', 
         nbr_lot: 1, 
         mode_id: 5,
         periode_lanc: '23-03-2021',
         periode_remise: '28-03-2021',
         temp: 1,
         date_prob_demarrage: '12-04-2021',
         delai_exe: 30, 
         date_prob_fin: '12-05-2021',
         gestionnaire: 'DRO',
         type_id: 1,
         localisation_id: 2
         },
         {id: 8, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '220', 
          montant_estime: 2500000, 
          montant_depense: 0, 
          credit: 2500000, 
          designation: 'Fourniture et pose de deux bacs  à ordures au nouveau siège de la DRO', 
          nbr_lot: 1, 
          mode_id: 5,
          periode_lanc: '23-03-2021',
          periode_remise: '28-03-2021',
          temp: 1,
          date_prob_demarrage: '12-04-2021',
          delai_exe: 60, 
          date_prob_fin: '11-06-2021',
          gestionnaire: 'DRO',
          type_id: 2,
          localisation_id: 2
          },
          {id: 9, 
           plan_id: 1, 
           budget_id: 1, 
           imputation: '612', 
           montant_estime: 33000000, 
           montant_depense: 0, 
           credit: 33000000, 
           designation: 'Fourniture de bureau , de produits d\'entretien et d\'imprimés', 
           nbr_lot: 3, 
           mode_id: 4,
           periode_lanc: '26-03-2021',
           periode_remise: '05-04-2021',
           temp: 1,
           date_prob_demarrage: '20-04-2021',
           delai_exe: 360, 
           date_prob_fin: '15-04-2022',
           gestionnaire: 'DRO',
           type_id: 2,
           localisation_id: 2
           },
          //***************************** PLAN DE PASSATION DES MARCHES DE LA DIRECTION REGIONALE DU NORD**********/
          {id: 10, 
          plan_id: 1, 
          budget_id: 1, 
          imputation: '220', 
          montant_estime: 1355000, 
          montant_depense: 0, 
          credit: 1355000, 
          designation: 'Acquisition et installation d’un polytank avec surpresseur à la villa d\'acceuil de Ouahigouya et acquisition et installation d’un surpresseur à la villa de logement du DR Ouahigouya', 
          nbr_lot: 1, 
          mode_id: 5,
          periode_lanc: '23-03-2021',
          periode_remise: '28-03-2021',
          temp: 1,
          date_prob_demarrage: '12-04-2021',
          delai_exe: 60, 
          date_prob_fin: '11-06-2021',
          gestionnaire: 'DRN',
          type_id: 2,
          localisation_id: 3
          },
          //***************************** PLAN DE PASSATION DES MARCHES DE LA DIRECTION REGIONALE DE FADA N'GOURMA**********/
          {id: 11, 
            plan_id: 1, 
            budget_id: 1, 
            imputation: '612', 
            montant_estime: 9200000, 
            montant_depense: 0, 
            credit: 9200000, 
            designation: 'Fourniture de bureau , de produits d\'entretien et d\'imprimés', 
            nbr_lot: 3, 
            mode_id: 6,
            periode_lanc: '05-03-2021',
            periode_remise: '10-03-2021',
            temp: 1,
            date_prob_demarrage: '17-03-2021',
            delai_exe: 360, 
            date_prob_fin: '12-03-2022',
            gestionnaire: 'DRF',
            type_id: 2,
            localisation_id: 4
          },
            //***************************** PLAN DE PASSATION DES MARCHES DE LA DIRECTION REGIONALE DE DEDOUGOU**********/
          {id: 12, 
            plan_id: 1, 
            budget_id: 1, 
            imputation: '612', 
            montant_estime: 7750000, 
            montant_depense: 0, 
            credit: 7750000, 
            designation: 'Fourniture de bureau , de produits d\'entretien et d\'imprimés', 
            nbr_lot: 3, 
            mode_id: 6,
            periode_lanc: '01-03-2021',
            periode_remise: '06-03-2021',
            temp: 1,
            date_prob_demarrage: '31-03-2021',
            delai_exe: 360, 
            date_prob_fin: '16-03-2022',
            gestionnaire: 'DRD',
            type_id: 2,
            localisation_id: 5
          },
             //***************************** PLAN DE PASSATION DES MARCHES DE LA DIRECTION REGIONALE DE BOBO-DIOULASSO**********/
          {id: 13, 
            plan_id: 1, 
            budget_id: 1, 
            imputation: '638', 
            montant_estime: 45278039, 
            montant_depense: 0, 
            credit: 45278039, 
            designation: 'Prestation de gardiennage des services', 
            nbr_lot: 1, 
            mode_id: 14,
            periode_lanc: '01-01-2021',
            periode_remise: '01-01-2021',
            temp: 1,
            date_prob_demarrage: '11-01-2021',
            delai_exe: 360, 
            date_prob_fin: '06-01-2022',
            gestionnaire: 'DRB',
            type_id: 2,
            localisation_id: 6
          },
           
        
      ]);
    });
};
