--------------------------------------------------------
--  Fichier créé - mercredi-septembre-07-2022   
--------------------------------------------------------
REM INSERTING into GCP."dossiers"
SET DEFINE OFF;
Insert into GCP."dossiers" ("id","planitem_id","numero_doss","intitule_doss","date_trans_sign","date_retour_sign","date_trans_dgcmef","taux_reception","niveau_traitement","taux_avencement","dossier","statut","created_by","modified_by","created_at","updated_at") values ('1','130','DPX 2022/00001/CNSS/undefined/SAP','FOURNITURE DE BUREAU, PRODUITS D''ENTRETIEN ET D''IMPRIMES','2022-09-14','2022-09-28','2022-09-29',null,null,null,null,'Valider',null,null,null,null);
Insert into GCP."dossiers" ("id","planitem_id","numero_doss","intitule_doss","date_trans_sign","date_retour_sign","date_trans_dgcmef","taux_reception","niveau_traitement","taux_avencement","dossier","statut","created_by","modified_by","created_at","updated_at") values ('3','133','DPX 2022/00001/CNSS/DESG/SM','Travaux de réfection de deux villas à Bobo Dioulasso','2022-09-29','2022-09-20','2022-09-13',null,null,null,'C:\fakepath\Guide-dutilisation-NQ.pdf','Valider',null,null,null,null);
Insert into GCP."dossiers" ("id","planitem_id","numero_doss","intitule_doss","date_trans_sign","date_retour_sign","date_trans_dgcmef","taux_reception","niveau_traitement","taux_avencement","dossier","statut","created_by","modified_by","created_at","updated_at") values ('2','131','DPX 2022/00001/CNSS/undefined/SAP','Nettoyage des locaux de la Dro siège et des Agences de Dassasgho, Kilwin et Koudougou','2022-09-07','2022-09-08','2022-09-12',null,null,null,null,'Valider',null,null,null,null);
Insert into GCP."dossiers" ("id","planitem_id","numero_doss","intitule_doss","date_trans_sign","date_retour_sign","date_trans_dgcmef","taux_reception","niveau_traitement","taux_avencement","dossier","statut","created_by","modified_by","created_at","updated_at") values ('4','133','DPX 2022/00001/CNSS/DESG/SM','Travaux de réfection de deux villas à Bobo Dioulasso','2022-09-29','2022-09-20','2022-09-13',null,null,null,'C:\fakepath\Guide-dutilisation-NQ.pdf','Valider',null,null,null,null);
Insert into GCP."dossiers" ("id","planitem_id","numero_doss","intitule_doss","date_trans_sign","date_retour_sign","date_trans_dgcmef","taux_reception","niveau_traitement","taux_avencement","dossier","statut","created_by","modified_by","created_at","updated_at") values ('5','133','DPX 2022/00005/CNSS/DESG/SM','Travaux de réfection de deux villas à Bobo Dioulasso','2022-09-13','2022-09-01','2022-08-29',null,null,null,'C:\fakepath\attestation-covid.pdf','Valider',null,null,null,null);
