--------------------------------------------------------
--  Fichier créé - mercredi-septembre-07-2022   
--------------------------------------------------------
REM INSERTING into GCP."planitems"
SET DEFINE OFF;
Insert into GCP."planitems" ("id","plan_id","num_ordre","budget","imputation","montant_estime","montant_depense","credit","designation","nbr_lot","mode","date_lanc","date_reel_lanc","date_remise","date_reel_remise","temp","temp_reel","date_prob_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_prob_fin","date_reel_fin","gestionnaire","type_id","localisation_id","created_by","modified_by","created_at","updated_at") values ('129','6',null,'Budget CNSS','612','12000000',null,'13000000','ACQUISITION DE CONSOMMABLES INFORMATIQUES','2','DPX','2022-09-12',null,'2022-09-22',null,'1',null,'2022-10-13',null,'30',null,'2026-05-22',null,'DESG','2','1',null,null,null,null);
Insert into GCP."planitems" ("id","plan_id","num_ordre","budget","imputation","montant_estime","montant_depense","credit","designation","nbr_lot","mode","date_lanc","date_reel_lanc","date_remise","date_reel_remise","temp","temp_reel","date_prob_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_prob_fin","date_reel_fin","gestionnaire","type_id","localisation_id","created_by","modified_by","created_at","updated_at") values ('132','6',null,'Budget CNSS','620','6250000','0','0','ACQUISITION DE PRODUITS D''ENTRETIEN','1','DC','2022-09-23',null,'2022-10-07',null,'1',null,'2022-10-24',null,'30',null,'2029-05-26',null,'DESG','2','1',null,null,null,null);
Insert into GCP."planitems" ("id","plan_id","num_ordre","budget","imputation","montant_estime","montant_depense","credit","designation","nbr_lot","mode","date_lanc","date_reel_lanc","date_remise","date_reel_remise","temp","temp_reel","date_prob_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_prob_fin","date_reel_fin","gestionnaire","type_id","localisation_id","created_by","modified_by","created_at","updated_at") values ('133','6',null,'Budget CNSS','226','18850000','0','18850000','Travaux de réfection de deux villas à Bobo Dioulasso','1','DPX','2022-09-20',null,'2022-09-30',null,'1',null,'2022-10-21',null,'90',null,'2028-09-28',null,'DESG','1','1',null,null,null,null);
Insert into GCP."planitems" ("id","plan_id","num_ordre","budget","imputation","montant_estime","montant_depense","credit","designation","nbr_lot","mode","date_lanc","date_reel_lanc","date_remise","date_reel_remise","temp","temp_reel","date_prob_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_prob_fin","date_reel_fin","gestionnaire","type_id","localisation_id","created_by","modified_by","created_at","updated_at") values ('130','6',null,'Budget CNSS','612','33000000',null,'33000000','FOURNITURE DE BUREAU, PRODUITS D''ENTRETIEN ET D''IMPRIMES','3','DPX','2022-09-06',null,'2022-09-16',null,'1',null,'2022-09-16',null,'90',null,'2024-11-28',null,'SAP','2','2',null,null,null,null);
Insert into GCP."planitems" ("id","plan_id","num_ordre","budget","imputation","montant_estime","montant_depense","credit","designation","nbr_lot","mode","date_lanc","date_reel_lanc","date_remise","date_reel_remise","temp","temp_reel","date_prob_demarrage","date_reel_demarrage","delai_exe","delai_reel_exe","date_prob_fin","date_reel_fin","gestionnaire","type_id","localisation_id","created_by","modified_by","created_at","updated_at") values ('131','6',null,'Budget CNSS','63310','15000000','0','15000000','Nettoyage des locaux de la Dro siège et des Agences de Dassasgho, Kilwin et Koudougou','2','DPX','2022-09-07',null,'2022-09-17',null,'1',null,'2022-01-01',null,'90',null,'2022-12-31',null,'DESG','2','2',null,null,null,null);
